# Generated by Django 3.1.3 on 2022-07-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220729_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('BARR', 'Barr'), ('DR', 'Dr'), ('ENGR', 'Engr'), ('PROF', 'Prof')], default='', max_length=6),
        ),
    ]
