# Generated by Django 4.0.6 on 2022-07-27 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skillsets', '0001_initial'),
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='article_category', to='skillsets.jobcategory'),
        ),
        migrations.AlterField(
            model_name='article',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='article_category', to='skillsets.job'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='subcategory',
            field=models.ManyToManyField(blank=True, related_name='article_category', to='skillsets.jobsubcategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='article_tag', to='articles.tag'),
        ),
    ]
