# Generated by Django 4.0.6 on 2022-07-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0002_rename_name_job_title_remove_job_association_and_more'),
        ('users', '0005_rename_model_id_review_object_id_and_more'),
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='job',
            field=models.ManyToManyField(related_name='job', to='skillsets.job'),
        ),
        migrations.AddField(
            model_name='ad',
            name='job_category',
            field=models.ManyToManyField(related_name='job_category', to='skillsets.jobcategory'),
        ),
        migrations.AddField(
            model_name='ad',
            name='job_subcategory',
            field=models.ManyToManyField(related_name='job_subcategory', to='skillsets.jobsubcategory'),
        ),
        migrations.AddField(
            model_name='ad',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ad',
            name='related_company',
            field=models.ManyToManyField(related_name='related_company', to='users.company'),
        ),
        migrations.AddField(
            model_name='ad',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='video_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
