# Generated by Django 4.0.6 on 2022-07-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_birthday_alter_user_city_and_more'),
        ('skillsets', '0001_initial'),
        ('ads', '0003_alter_ad_job_alter_ad_job_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='ad_model_job', to='skillsets.job'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='job_category',
            field=models.ManyToManyField(blank=True, related_name='ad_model_job_category', to='skillsets.jobcategory'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='job_subcategory',
            field=models.ManyToManyField(blank=True, related_name='ad_model_job_subcategory', to='skillsets.jobsubcategory'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='related_company',
            field=models.ManyToManyField(blank=True, related_name='related_company', to='users.company'),
        ),
    ]
