# Generated by Django 4.0.6 on 2022-07-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0002_rename_name_job_title_remove_job_association_and_more'),
        ('ads', '0003_ad_active_ad_job_ad_job_category_ad_job_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='job',
            field=models.ManyToManyField(related_name='ad_model_job', to='skillsets.job'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='job_category',
            field=models.ManyToManyField(related_name='ad_model_job_category', to='skillsets.jobcategory'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='job_subcategory',
            field=models.ManyToManyField(related_name='ad_model_job_subcategory', to='skillsets.jobsubcategory'),
        ),
    ]
