# Generated by Django 4.0.6 on 2022-07-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(blank=True, default='', max_length=12)),
                ('description', models.TextField(default='')),
                ('city', models.CharField(blank=True, default='', max_length=32)),
                ('lga', models.CharField(blank=True, default='', max_length=32)),
                ('state', models.CharField(blank=True, default='', max_length=32)),
                ('country', models.CharField(blank=True, default='', max_length=32)),
                ('phone', models.CharField(blank=True, default='', max_length=24)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
