# Generated by Django 4.0.6 on 2022-07-26 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skillsets', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='alumni',
            field=models.ManyToManyField(related_name='graduates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institution',
            name='category',
            field=models.ManyToManyField(related_name='job_categories', to='skillsets.jobcategory'),
        ),
        migrations.AddField(
            model_name='institution',
            name='job',
            field=models.ManyToManyField(related_name='institution_job', to='skillsets.job'),
        ),
        migrations.AddField(
            model_name='institution',
            name='subcategory',
            field=models.ManyToManyField(related_name='job_subcategories', to='skillsets.jobsubcategory'),
        ),
    ]
