# Generated by Django 4.0.6 on 2022-07-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.CharField(choices=[('GI', 'General Information'), ('I', 'Interviews'), ('N', 'News')], default='GI', max_length=2),
        ),
    ]
