# Generated by Django 4.0.6 on 2022-07-30 14:45

import articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0014_alter_article_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
