# Generated by Django 4.0.6 on 2022-07-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0007_alter_job_id_alter_jobcategory_id_and_more'),
        ('articles', '0017_alter_article_job_alter_article_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='article_skills', to='skillsets.skill'),
        ),
    ]
