# Generated by Django 4.0.6 on 2022-08-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_alter_article_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.CharField(choices=[('general', 'General'), ('interviews', 'Interviews'), ('news', 'News')], default='general', max_length=12),
        ),
    ]
