# Generated by Django 4.0.6 on 2022-08-11 23:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0011_alter_job_id_alter_jobcategory_id_and_more'),
        ('education', '0006_alter_institution_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='alumni',
        ),
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('overview', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=32)),
                ('lga', models.CharField(blank=True, default='', max_length=32)),
                ('state', models.CharField(blank=True, default='', max_length=32)),
                ('country', models.CharField(blank=True, default='', max_length=32)),
                ('phone', models.CharField(blank=True, default='', max_length=24)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('online', models.BooleanField(default=False)),
                ('cost', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('certificate_type', models.CharField(blank=True, choices=[('B. Eng', 'B. Eng'), ('MSc', 'Msc')], max_length=128)),
                ('level', models.CharField(choices=[('Masters degree', 'Masters degree'), ('Bachelors degree', 'Bachelors degree'), ('Secondary Certificate', 'Secondary Certificate')], max_length=32)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_institution', to='education.institution')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_institution', to='skillsets.job')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_institution', to='skillsets.skill')),
            ],
        ),
    ]
