# Generated by Django 4.0.6 on 2022-07-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0002_alter_jobcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='outlook_summary',
            field=models.CharField(max_length=32),
        ),
    ]
