# Generated by Django 4.0.6 on 2022-07-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0003_alter_jobcategory_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='job',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='job',
            name='outlook_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='outlook_summary',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='roles',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skillsets.skill'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skillsets.skill'),
        ),
        migrations.AddField(
            model_name='jobsubcategory',
            name='outlook_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsubcategory',
            name='outlook_summary',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='jobsubcategory',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skillsets.skill'),
        ),
        migrations.AlterField(
            model_name='jobsubcategory',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
