# Generated by Django 4.0.6 on 2022-07-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0007_alter_job_id_alter_jobcategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='outlook_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='outlook_summary',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
