# Generated by Django 4.0.6 on 2022-07-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('message', models.TextField(blank=True, default='')),
                ('video_link', models.URLField(blank=True, default='')),
                ('active', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, default='')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
