# Generated by Django 4.0.6 on 2022-07-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0001_initial'),
        ('users', '0004_alter_user_gender'),
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='job',
            field=models.ManyToManyField(blank=True, null=True, related_name='ad_model_job', to='skillsets.job'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='job_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='ad_model_job_category', to='skillsets.jobcategory'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='job_subcategory',
            field=models.ManyToManyField(blank=True, null=True, related_name='ad_model_job_subcategory', to='skillsets.jobsubcategory'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='related_company',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_company', to='users.company'),
        ),
    ]
