# Generated by Django 4.0.6 on 2022-08-03 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0006_alter_ad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertizer_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
