# Generated by Django 4.0.6 on 2022-08-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0008_skill_outlook_details_skill_outlook_summary'),
        ('ads', '0007_alter_ad_advertizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='ad_model_skills', to='skillsets.skill'),
        ),
    ]
