# Generated by Django 4.0.6 on 2022-08-11 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0010_alter_ad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='general_clicks',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='user_clicks',
            field=models.ManyToManyField(blank=True, related_name='user_ad_clicks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
