# Generated by Django 4.0.6 on 2022-08-12 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_ad_general_clicks_ad_user_clicks_ad_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
