# Generated by Django 4.0.6 on 2022-07-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_birthday_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='author',
            field=models.CharField(choices=[('N', 'NO'), ('P', 'PENDING'), ('Y', 'YES')], default='N', max_length=1),
        ),
    ]
