# Generated by Django 4.0.6 on 2022-08-02 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_alter_article_approver'),
        ('users', '0013_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='object_model',
        ),
        migrations.AddField(
            model_name='review',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
