# Generated by Django 4.0.6 on 2022-08-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_company_name_alter_company_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='author',
            field=models.CharField(choices=[('No', 'No'), ('Pending', 'Pending'), ('Yes', 'Yes')], default='No', max_length=7),
        ),
    ]
