# Generated by Django 4.0.6 on 2022-08-11 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_alter_article_id_alter_tag_id'),
        ('skillsets', '0012_level_rename_roles_job_regulations_job_association_and_more'),
        ('education', '0007_remove_institution_alumni_institution_address_course'),
        ('users', '0019_alter_association_id_alter_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='job',
        ),
        migrations.RemoveField(
            model_name='association',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='association',
            name='job_subcategory',
        ),
        migrations.RemoveField(
            model_name='association',
            name='members',
        ),
        migrations.RemoveField(
            model_name='association',
            name='skill',
        ),
        migrations.AddField(
            model_name='company',
            name='association',
            field=models.ManyToManyField(blank=True, related_name='company_associations', to='users.association'),
        ),
        migrations.AddField(
            model_name='company',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='company_job', to='skillsets.job'),
        ),
        migrations.AddField(
            model_name='company',
            name='job_category',
            field=models.ManyToManyField(blank=True, related_name='company_job_category', to='skillsets.jobcategory'),
        ),
        migrations.AddField(
            model_name='company',
            name='job_subcategory',
            field=models.ManyToManyField(blank=True, related_name='company_job_subcategory', to='skillsets.jobsubcategory'),
        ),
        migrations.AddField(
            model_name='review',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='association_review', to='users.association'),
        ),
        migrations.AddField(
            model_name='review',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_review', to='users.company'),
        ),
        migrations.AddField(
            model_name='review',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_review', to='skillsets.job'),
        ),
        migrations.AddField(
            model_name='review',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_category_review', to='skillsets.jobcategory'),
        ),
        migrations.AddField(
            model_name='review',
            name='job_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_subcategory_review', to='skillsets.jobsubcategory'),
        ),
        migrations.AddField(
            model_name='review',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_review', to='skillsets.level'),
        ),
        migrations.AddField(
            model_name='review',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_review', to='skillsets.skill'),
        ),
        migrations.AddField(
            model_name='user',
            name='association',
            field=models.ManyToManyField(blank=True, related_name='user_associations', to='users.association'),
        ),
        migrations.AddField(
            model_name='userqualification',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_qualification_course', to='education.course'),
        ),
        migrations.AddField(
            model_name='userqualification',
            name='ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userqualification',
            name='started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userqualification',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userworkprofile',
            name='monthly_salary',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_review', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='userworkprofile',
            name='level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='skillsets.level'),
        ),
    ]
