# Generated by Django 4.0.6 on 2022-07-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0004_remove_skill_category_remove_skill_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='outlook_summary',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
