# Generated by Django 4.0.6 on 2022-08-03 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0008_skill_outlook_details_skill_outlook_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='job',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_sub_category', to='skillsets.jobsubcategory'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='description',
            field=models.TextField(),
        ),
    ]
